backend:
  name: git-gateway
  branch: main # Or your default branch
  base_url: "/astro-test" # Your repository name
  site_domain: "renatostellarelmts.github.io"
media_folder: public/img
public_folder: /img
collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
